- name: PLAY-1
  hosts: local host
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "Hello, I'm Saikumar from PLAY-1 and TASK-1"


- name: PLAY-2
  hosts: local host
  tasks:
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug:
      msg: "Hello, I'm Saikumar from PLAY-2 and TASK-2"
