
- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} # state latest means to install 
    - { name: 'nginx', state: 'absent'} # state absent means to uninstall
    - { name: 'postfix', state: 'absent'}